### ISSUE TITLE
Ordered consumer

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#589]
**Problem**
We need ordered message consumptions to cover a range of use cases

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? User

**Exit Criteria**
An option to setup ordered consumption of topics

**Steps**

* [x] Refactor the Consumer verticle and friends to make room for ordered consumer #614 #628
* [x] Implement ordered consumer verticle #639
* [x] Add to the contract the ordered/unordered for the egress #689
* [x] Define an API to expose ordered/unordered consumer and implement it #701
* [x] Docs https://github.com/knative/docs/pull/3369
* [x] Add DeliveryOrder status condition or annotation for Trigger #732
* [x] Add a test with more partitions using the partition key to check the ordered delivery across partitions #756

**Comment by slinkydeveloper** [comment]
In order to develop an ordered consumer, we need a FSM that polls the consumer and process the events. More details to come

**Comment by pierDipi** [comment]
_Note: this is not part of this issue, just sharing an idea._

What do you think about having 2 topics?

The reasoning being that when there is no `partitionkey` the order is "random" from a user perspective and they don't care about ordering, so we can have 2 topics:

1. 1 topic for strictly order delivery
1. 1 topic for unordered delivery

The receiver sends events to (1) when there is a `partitionkey` set and to (2) when there is not.
The dispatcher can: 
1. instantiate a consumer for (1) respecting strictly ordered delivery and a consumer for (2) with a parallel consumer. Or
1. instantiate a consumer for (1) and (2) and route events to a component based on the topic.

**Comment by slinkydeveloper** [comment]
TBH I'm not sure the effort is worth and ends up in a reasonable speedup. In any case, I'm going to implement the ordered consumer without removing the unordered consumer, so this will be an option to turn it on (then on next release, we make it default)

**Comment by pierDipi** [comment]
We can consider this one: https://github.com/confluentinc/parallel-consumer

**Comment by pierDipi** [comment]
There is a Vert.x integration too.

**Comment by pierDipi** [comment]
> Why not use the Vert.x library yourself in your processing loop?
> 
> - Vert.x us used in this library to provide a non-blocking IO system in the message processing step. Using Vert.x without using this library with ordered processing requires dealing with the quite complicated, and not straight forward, aspect of handling offset commits with Vert.x asynchronous processing system.
> 
> - Unordered processing with Vert.x is somewhat easier, however offset management is still quite complicated, and the Parallel Consumer also provides optimizations for message-level acknowledgment in this case. This library handles offset commits for both ordered and unordered processing cases.

**Comment by slinkydeveloper** [comment]
> ordered processing requires dealing with the quite complicated, and not straight forward, aspect of handling offset commits with Vert.x asynchronous processing system.

Mwah, I'm not of the same opinion, as you see from https://github.com/knative-sandbox/eventing-kafka-broker/pull/597 that's quite straightforward. If messages are ordered, it's even more straightforward to handle offsets. It sounds more like their reason was not to couple to Vert.x itself...

**Comment by slinkydeveloper** [comment]
With #639 in place, now we need to figure out the API to expose the configuration "ordered"/"unordered" to the user. How do we want to do that? How about a trigger annotation?

**Comment by pierDipi** [comment]
It's ok for me as an annotation.

- annotation: `kafka.eventing.knative.dev/delivery: (ordered | unordered)` 
- a condition in the status indicating the delivery to have a feedback on this annotation.

WDYT?

**Comment by pierDipi** [comment]
On the annotation name, I'd probably need to think more carefully but we can defer this decision.

**Comment by slinkydeveloper** [comment]
@pierDipi I'm fine with that name

**Comment by pierDipi** [comment]
Also, we should loop in other folks to align `KafkaChannel` impl when this will be supported.

/cc @devguyio @matzew @lionelvillard

**Comment by pierDipi** [comment]
We should decide the default value as well that for now could be hardcoded.

**Comment by pierDipi** [comment]
> If we're going to implement kafka channel and kafka source

I'd love to have this at some point :)

**Comment by slinkydeveloper** [comment]
Since the ordered consumer is a new feature, I prefer to go with unordered as default

**Comment by pierDipi** [comment]
+1.

**Comment by slinkydeveloper** [comment]
All done :partying_face:
